IF_MATCH_MISSING = "Missing If-Match header when updating a resource"
IF_MATCH_INVALID = "If-Match header not matching current version"
CHEESE_ASSIGNED = "This cheese already has a zone assigned"
ZONE_ERROR = "Cheese: {} is not in from zone: {}."
ZONE_NOT_EXISTANT = "Zone {} doesn't exist"